---
title: "check_outputs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(sf)

# Step 1 output
out_1 <- read_csv(file.path(here::here(), "data", "int", "geoweights", "ca_counties_era5.csv"))

# Step 2 output
out_2 <- read_csv(file.path(here::here(), "data", "output", "ca_counties_era5_temp_2005_2010_polynomial_3.csv"))

# CA county shapefile for checking maps
us_counties <- tigris::counties()
ca_counties <- us_counties %>% 
  filter(STATEFP == '06')
```


# Check Step 1 Outputs

Step 1 output is the overlap between the California counties polygons and the climate rasters. There should be 58 polygons, representing the 58 counties in the state. 

```{r}
check_id_counts <- out_1 %>% 
  select(poly_id) %>% 
  distinct() #58 - good 

# Map by polygon color 
map_polys <- ggplot() + 
  geom_raster(data = out_1, aes(x=x, y=y, fill=poly_id),
              alpha = 0.8) +
  geom_sf(data = ca_counties, color = 'black', fill = NA) + 
  labs(x = '',
       y = '') + 
  theme_bw() + 
  theme(legend.position = '')

# Check x/y poly ids 
xy_ids <- out_1 %>% 
  group_by(x,y) %>% 
  summarize(n_poly_ids = n())

# Map weights 
# Weight = fraction of the cell covered by the polygon * area km 2
# Normalized by polygon so all polygons should sum to 1
map_weights <- ggplot() + 
  geom_raster(data = out_1, aes(x=x, y=y, fill=w_geo)) +
  geom_sf(data = ca_counties, color = 'black', fill = NA) + 
  labs(fill = 'Area Weight',
       x = '',
       y = '') + 
  scale_fill_viridis_c() + 
  theme_bw() 

# Check sum weights
sum_weights <- out_1 %>% 
  group_by(poly_id) %>% 
  mutate(sum_w_geo = sum(w_geo)) %>% 
  ungroup() # All = 1
```


# Check Step 2 Output

```{r}
# Check that each polygon has a value for all 12 months 
check_out2 <- out_2 %>% 
  group_by(year, poly_id) %>% 
  summarize(n_months = n()) # Some have 13? There's an NA value for 5 counties on top of the 12 months

# Check for any na values
check_nas <- out_2 %>% 
  filter(is.na(order_1) | is.na(order_2) | is.na(order_3)) # Just the 5 counties in each year (30 total)

na_counties <- ca_counties %>% 
  filter(GEOID %in% c('06015', '06023', '06025', '06071', '06073')) # San Diego, San Bernardino, Humboldt, Del Norte, Imperial 

# Convert the first order to avg temp by month so it's easier to understand the values 
# use value / days in month 
out_2 <- out_2 %>% 
  mutate(days_in_month = case_when(month %in% c('month_04', 'month_06', 'month_09', 'month_11') ~ 30,
                                   month == 'month_02' & year == 2008 ~ 29,
                                   month == 'month_02' & year != 2008 ~ 28, 
                                   TRUE ~ 31)) %>% 
  mutate(order_1_avg = order_1 / days_in_month)

# Check leap years
feb <- out_2 %>% 
  filter(month == 'month_02')

leap_plot <- ggplot() + 
  geom_line(data = feb, aes(x = year, y = order_1, color = as.factor(poly_id), group = poly_id)) + 
  geom_vline(xintercept = 2008,
             linetype = 'longdash') + 
  scale_x_continuous(expand = c(0,0),
                   breaks = seq(2005, 2010, by=1)) + 
  labs(x = 'Year',
       y = 'Avg February Temperatures') + 
  theme_bw() + 
  theme(legend.position = '')

## Graphs 
# Polynomial values over time by polygon (one graph for each polynomial order)
poly1_plot <- ggplot() + 
  geom_line(data = out_2, aes(x = month, y = order_1_avg, color = as.factor(poly_id), group = poly_id)) + 
  facet_wrap(~year) + 
  scale_x_discrete(expand = c(0,0),
                   breaks = c('month_01', 'month_03', 'month_05',
                              'month_07', 'month_09', 'month_11'),
                   labels = c('Jan', 'Mar', 'May', 'Jul',
                              'Sept', 'Nov')) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(-10,40),
                     breaks = seq(-10,40,10)) +
  labs(x = 'Month',
       y = 'Averarge Monthly Temp\n(First Order / Days in Month)') + 
  theme_bw() + 
  theme(legend.position = '')

poly2_plot <- ggplot() + 
  geom_line(data = out_2, aes(x = month, y = order_2, color = as.factor(poly_id), group = poly_id)) + 
  facet_wrap(~year) + 
  scale_x_discrete(expand = c(0,0),
                   breaks = c('month_01', 'month_03', 'month_05',
                              'month_07', 'month_09', 'month_11'),
                   labels = c('Jan', 'Mar', 'May', 'Jul',
                              'Sept', 'Nov')) + 
  scale_y_continuous(expand = c(0,0),
                     limits = c(100,42000)) +
  labs(x = 'Month',
       y = 'Summed Monthly Temperature (Second Order)') + 
  theme_bw() + 
  theme(legend.position = '')

poly3_plot <- ggplot() + 
  geom_line(data = out_2, aes(x = month, y = order_3, color = as.factor(poly_id), group = poly_id)) + 
  facet_wrap(~year) + 
  scale_x_discrete(expand = c(0,0),
                   breaks = c('month_01', 'month_03', 'month_05',
                              'month_07', 'month_09', 'month_11'),
                   labels = c('Jan', 'Mar', 'May', 'Jul',
                              'Sept', 'Nov')) + 
  scale_y_continuous(expand = c(0,0),
                     labels = scales::comma) +
  labs(x = 'Month',
       y = 'Summed Monthly Temperature (Third Order)') + 
  theme_bw() + 
  theme(legend.position = '')

## Maps 
# Join first order outputs to the shp 
ca_counties <- ca_counties %>% 
  mutate(poly_id = as.numeric(GEOID)) %>% 
  select(poly_id)

out_2 <- out_2 %>% 
  filter(!is.na(month))

out2_sf <- merge(ca_counties, out_2, all = TRUE)

# Map first order values by county for lowest temp month (Feb) 
map_order1_feb <- out2_sf %>% 
  filter(month == 'month_02') %>% 
  ggplot() + 
  geom_sf(aes(fill = order_1_avg)) + 
  labs(fill = 'Avg Feb\nTemperature\n(1st Order)',
       x = '',
       y = '') + 
  scale_fill_viridis_c() + 
  facet_wrap(~year) + 
  theme_bw() 

# Map first order values for highest temp month (July)
map_order1_jul <- out2_sf %>% 
  filter(month == 'month_07') %>% 
  ggplot() + 
  geom_sf(aes(fill = order_1_avg)) + 
  labs(fill = 'Avg July\nTemperature\n(1st Order)',
       x = '',
       y = '') + 
  scale_fill_viridis_c() + 
  facet_wrap(~year) + 
  theme_bw() 
```

